apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
  labels:
    name: javadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javadeployment
  template:
    metadata:
      labels:
        app: javadeployment
    spec:
      containers:
      - name: javadeployment
        image: mohamaddiwany/devopstaskimg
        ports:
        - containerPort: 8080

    spec:
      containers:
      - image: mysql:5.7.8
        name: mysql
        env:
	- name:MYSQL_USER
	  value: petclinic
	- name:MYSQL_PASSWORD
	  value: petclinic
	- name:MYSQL_ROOT_PASSWORD
	  value:root
	- name:MYSQL_DATABASE
	  value:petclinic
        ports:
        - containerPort: 3306
          name: mysql
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: javaservice
spec:
  selector:
    app: javadeployment
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: databaseconfig
data:
  MYSQL_ROOT_PASSWORD : "root"
  MYSQL_ALLOW_EMPTY_PASSWORD : "true"
  MYSQL_USER : "petclinic"
  MYSQL_PASSWORD : "petclinic"
  MYSQL_DATABASE : "petclinic"